- StitchCore/StitchCore/Source/Core/StitchClient.swift
`register` on the the `StitchClient` currently returns a 404, removing the trailing slash in the URL seems to fix it.
> STITCH-1016 - Fix broken email registration endpoint

- StitchCore/StitchCore/Source/Auth/AuthProvider.swift
- StitchCore/StitchCore/Source/Auth/AuthProviderInfo.swift
- StitchCore/StitchCore/Source/Auth/Providers/Anonymous/AnonymousAuthProvider.swift
- StitchCore/StitchCore/Source/Auth/Providers/ApiKey/ApiKeyAuthProvider.swift
- StitchCore/StitchCore/Source/Auth/Providers/Custom/CustomAuthProvider.swift
- StitchCore/StitchCore/Source/Auth/Providers/EmailPassword/EmailPasswordAuthProvider.swift
- StitchCore/StitchCore/Source/Auth/Providers/Facebook/FacebookAuthProvider.swift
- StitchCore/StitchCore/Source/Auth/Providers/Google/GoogleAuthProvider.swift
- StitchCore/StitchCore/Source/Core/StitchClient.swift
- StitchCore/StitchCore/Source/Core/StitchHTTPClient.swift
- StitchCore/StitchCoreTests/AuthTests.swift
In this change I now keep track of the auth provider used to log into a session in a new UserDefaults key, I exposed that in the StitchClient, and I updated `login()` to use the expected semantics.
**Drive-by changes:**
- Updated the enum of AuthProviderTypes to be `internal` rather than `private` so I could compare the types in the `StitchClient`. 
- Changed the hardcoded types in each of the the auth providers to the raw value of the enum type
> STITCH-1040 Improve semantics of multiple logins

- StitchCore/StitchCore/Source/Auth/AuthInfo.swift
- StitchCore/StitchCore/Source/Core/StitchClient.swift
- StitchCore/StitchCoreTests/AuthTests.swift
This change adds linking functionality to the iOS SDK. Should be functionally identical to the JS SDK changes, except that linking in the iOS SDK does not attempt to update the underlying auth object of StitchClient. I also made `loggedInProvider` always reflect the most recently linked identity to match the behavior of the JS SDK.
I tested this locally with an emal/password identity but until we can use the admin API in our tests it’s going to be difficult to test this. I left the test in as a comment.
**Drive-bys:**
- Made StitchClient in multiple login semantics test conform to new factory pattern
- Made `deviceID` and `refreshToken` optional in `AuthInfo` struct so the `decode()` doesn’t fail when getting the linking auth response
- refactored the `doLoginRequest()` closure from …
> STITCH-1075: iOS SDK Add ability for a user to link to any non-anonymous identity

- StitchCore/StitchCore/Source/Core/StitchClient.swift
- StitchCore/StitchCore/Source/Core/StitchHTTPClient.swift
- StitchCore/StitchCoreTests/AuthTests.swift
Really small fix with one drive-by change to fix compilation since a method was referencing userDefaults instead of storage. Didn't write any tests since the multiple login semantics test should catch this case when running on an iPhone.
> STITCH-1175 correctly delete isLoggedInUDKey in clearAuth()

- StitchCore/StitchCore/Source/Core/StitchHTTPClient.swift
token refresh was looking for "auth_info" and not "access_token" in the session post response
> fix token refresh

- StitchCore-iOS/StitchCore-iOS.xcodeproj/project.pbxproj
- StitchCore-iOS/StitchCore-iOS/Core/Internal/StitchAppClientImpl.swift
- StitchCore-iOS/StitchCore-iOS/Core/Stitch.swift
- StitchCore-iOS/StitchCore_iOSTests/Core/StitchTests.swift
- StitchCore/Sources/StitchCore/StitchAppClientConfiguration.swift
- StitchCore/Sources/StitchCore/StitchAppClientInfo.swift
- StitchCore/Sources/StitchCore/StitchClientConfiguration.swift
- StitchCore/Tests/stitch-ios-sdk-protoTests/StitchAppClientInfoTests.swift
Adds support for configuring an optional data directory for a Stitch app client. On iOS, this is set by default to the "Application Support" directory in the app's sandboxed filesystem. This was selected because of this description in the Apple docs:
"In general, this directory includes files that the app uses to run but that should remain hidden from the user. This directory can also include data files, configuration files, templates and modified versions of resources loaded from the app bundle."
The "Application Support" directory is also backed up by default.
> STITCH-1346 Add support for configuring data directory in StitchAppClient

- StitchCore-iOS/StitchCore-iOS/Core/Auth/Internal/StitchAuthImpl.swift
- StitchCore-iOS/StitchCore-iOS/Core/Auth/StitchAuth.swift
- StitchCore-iOS/StitchCore-iOS/Core/StitchCore.swift
- StitchCore/Sources/StitchCore/Auth/Internal/CoreStitchAuth+StitchAuthRequestClient.swift
- StitchCore/Sources/StitchCore/Auth/Internal/CoreStitchAuth.swift
- StitchCore/Sources/StitchCore/Internal/Net/FoundationHTTPTransport.swift
- StitchCore/Sources/StitchCore/Internal/Net/StitchRequestClient.swift
- StitchCore/Sources/StitchCore/StitchError.swift
- StitchCore/Tests/stitch-ios-sdk-protoTests/Auth/Internal/AccessTokenRefresherTests.swift
- StitchCore/Tests/stitch-ios-sdk-protoTests/Auth/Internal/CoreStitchAuthTests.swift
- StitchCore/Tests/stitch-ios-sdk-protoTests/Internal/Net/FoundationHTTPTransportTests.swift
- StitchCore/Tests/stitch-ios-sdk-protoTests/Internal/Net/StitchRequestClientTests.swift
- StitchCore/Tests/stitch-ios-sdk-protoTests/StitchAppClientConfigurationTests.swift
- StitchCore/Tests/stitch-ios-sdk-protoTests/StitchClientConfigurationTests.swift
I tried to refactor errors to be as consistent and cohesive as possible. It’s not too many changes, but I did think a lot about it as well as all of the edge cases. I’m happy to clarify anything
The gist of the change is that there now only three types of errors ever thrown by the SDK:
- `StitchClientError`: errors thrown before a request is made
- `StitchError`: errors thrown after a request is completed and a response is received
- Transport-specific errors: errors thrown while a request is being carried out (timeouts, could not reach server, etc.)
Main changes:
- StitchError now only represents errors that are from completed requests.
- We now have `case unknownError` in `StitchError`
- We no longer have `case requestError`. Instances were either replaced with an appropriate …
> STITCH-1354 Refactor error handling

- StitchCore-iOS/StitchCore-iOS.xcodeproj/project.pbxproj
- StitchCore-iOS/StitchCore-iOS/Core/Internal/StitchAppClientImpl.swift
- StitchCore-iOS/StitchCore-iOS/Core/Stitch.swift
- StitchCore-iOS/StitchCore-iOS/Core/StitchAppClient.swift
- StitchCore-iOS/StitchCore-iOS/Services/Internal/StitchService.swift
- StitchCore-iOS/StitchCore-iOS/Services/Internal/StitchServiceImpl.swift
- StitchCore-iOS/StitchCore_iOSTests/Core/StitchAppClientIntegrationAuthTests.swift
- StitchCore-iOS/StitchCore_iOSTests/Core/StitchAppClientIntegrationTests.swift
- StitchCore/Sources/StitchCore-AdminClient/StitchAdminClient.swift
- StitchCore/Sources/StitchCore/Auth/Internal/CoreStitchAuth+StitchAuthRequestClient.swift
- StitchCore/Sources/StitchCore/Auth/Internal/StitchAuthRequestClient.swift
- StitchCore/Sources/StitchCore/Internal/CoreStitchAppClient.swift
- StitchCore/Sources/StitchCore/Internal/Net/FoundationHTTPTransport.swift
- StitchCore/Sources/StitchCore/Internal/Net/Requests/Request.swift
- StitchCore/Sources/StitchCore/Internal/Net/Requests/StitchAuthRequest.swift
- StitchCore/Sources/StitchCore/Internal/Net/Requests/StitchRequest.swift
- StitchCore/Sources/StitchCore/Internal/Net/StitchRequestClient.swift
- StitchCore/Sources/StitchCore/Services/Internal/CoreStitchService.swift
- StitchCore/Sources/StitchCore/StitchAppClientConfiguration.swift
- StitchCore/Sources/StitchCore/StitchClientConfiguration.swift
- StitchCore/Sources/StitchCore/StitchError.swift
- StitchCore/Tests/stitch-ios-sdk-protoTests/Auth/Internal/CoreStitchAuthTests.swift
- StitchCore/Tests/stitch-ios-sdk-protoTests/Auth/Providers/UserPass/CoreUserPasswordAuthProviderClientTests.swift
- StitchCore/Tests/stitch-ios-sdk-protoTests/Internal/Net/FoundationHTTPTransportTests.swift
- StitchCore/Tests/stitch-ios-sdk-protoTests/Internal/Net/StitchRequestClientTests.swift
- StitchCore/Tests/stitch-ios-sdk-protoTests/StitchAppClientConfigurationTests.swift
- StitchCore/Tests/stitch-ios-sdk-protoTests/StitchClientConfigurationTests.swift
- StitchCore/Tests/stitch-ios-sdk-protoTests/stitch_ios_sdk_protoTests.swift
This was pretty straightforward change, I added a transport timeout `TimeInterval` to client configuration, and I modified `doRequest` in the `StitchRequestClient` to perform the Transport round trip on a background dispatch queue, using the `DispatchGroup.wait(timeout:)` method to measure the timeout. 
I added a timeout test, updated the config tests, and also refactored the client initialization method in `Stitch.swift` to address a Swiftlint cyclomatic complexity violation that arose with the changes.
> STITCH-1316 Handle Transport timeouts

- .evg.yml
- .gitignore
- Makefile
- Stitch.xcworkspace/contents.xcworkspacedata
- StitchCoreAdminClient/Sources/StitchCoreAdminClient/Services/ServiceConfigs.swift
- StitchCoreServicesHttp-iOS/StitchCoreServicesHttp-iOS.xcodeproj/project.pbxproj
- StitchCoreServicesHttp-iOS/StitchCoreServicesHttp-iOS.xcodeproj/xcshareddata/xcschemes/StitchCoreServicesHttp-iOS.xcscheme
- StitchCoreServicesHttp-iOS/StitchCoreServicesHttp-iOS/HttpServiceClient.swift
- StitchCoreServicesHttp-iOS/StitchCoreServicesHttp-iOS/Info.plist
- StitchCoreServicesHttp-iOS/StitchCoreServicesHttp-iOS/Internal/HttpServiceClientImpl.swift
- StitchCoreServicesHttp-iOS/StitchCoreServicesHttp-iOS/StitchCoreServicesHttp_iOS.h
- StitchCoreServicesHttp-iOS/StitchCoreServicesHttp-iOSTests/Info.plist
- StitchCoreServicesHttp-iOS/StitchCoreServicesHttp-iOSTests/StitchCoreServicesHttp_iOSTests.swift
- StitchCoreServicesHttp/.gitignore
- StitchCoreServicesHttp/Makefile
- StitchCoreServicesHttp/Package.swift
- StitchCoreServicesHttp/README.md
- StitchCoreServicesHttp/Sources/StitchCoreServicesHttp/HttpCookie.swift
- StitchCoreServicesHttp/Sources/StitchCoreServicesHttp/HttpMethod.swift
- StitchCoreServicesHttp/Sources/StitchCoreServicesHttp/HttpRequest.swift
- StitchCoreServicesHttp/Sources/StitchCoreServicesHttp/HttpResponse.swift
- StitchCoreServicesHttp/Sources/StitchCoreServicesHttp/Internal/CoreHttpServiceClient.swift
- StitchCoreServicesHttp/StitchCoreServicesHttp.xcconfig
- StitchCoreServicesHttp/Tests/StitchCoreServicesHttpTests/HttpRequestTests.swift
- StitchCoreServicesHttp/Tests/StitchCoreServicesHttpTests/Internal/CoreHttpServiceClientTests.swift
- contrib/README.md
almost no drivebys this time. `run_ios_tests` is still broken until we get them to reboot the box, but everything passes for me locally.
> STITCH-1371 Implement HTTP service in Core and iOS

- README.md
Shouldn't executeFunction be callFunction?
> Replace reference to executeFunction with callFunction

- Core/StitchCoreSDK/Sources/StitchCoreSDK/Auth/Internal/CoreStitchAuth+StitchAuthRequestClient.swift
- Core/StitchCoreSDK/Sources/StitchCoreSDK/Auth/Internal/CoreStitchAuth.swift
- Core/StitchCoreSDK/Tests/StitchCoreSDKTests/Auth/Internal/CoreStitchAuthUnitTests.swift
- Darwin/Services/StitchHTTPService/StitchHTTPServiceTests/HTTPServiceClientIntTests.swift
Instead of `objc_sync_enter`-ing on `self`, we now do it on two separate objects to mimic the logic of the Android SDK.
> STITCH-2159 Split locking for authing and auth state

- Core/Services/StitchCoreRemoteMongoDBService/Sources/StitchCoreRemoteMongoDBService/Sync/ChangeEventListener.swift
- Core/Services/StitchCoreRemoteMongoDBService/Sources/StitchCoreRemoteMongoDBService/Sync/CoreDocumentSynchronizationConfig.swift
- Core/Services/StitchCoreRemoteMongoDBService/Sources/StitchCoreRemoteMongoDBService/Sync/CoreSync.swift
- Core/Services/StitchCoreRemoteMongoDBService/Sources/StitchCoreRemoteMongoDBService/Sync/DataSynchronizer.swift
- Core/Services/StitchCoreRemoteMongoDBService/Sources/StitchCoreRemoteMongoDBService/Sync/ErrorListener.swift
- Core/Services/StitchCoreRemoteMongoDBService/Sources/StitchCoreRemoteMongoDBService/Sync/InstanceSynchronizationConfig.swift
- Core/Services/StitchCoreRemoteMongoDBService/Sources/StitchCoreRemoteMongoDBService/Sync/Log.swift
- Core/Services/StitchCoreRemoteMongoDBService/Sources/StitchCoreRemoteMongoDBService/Sync/NamespaceSynchronizationConfig.swift
- Core/Services/StitchCoreRemoteMongoDBService/StitchCoreRemoteMongoDBService.xcodeproj/project.pbxproj
- Core/Services/StitchCoreRemoteMongoDBService/Tests/StitchCoreRemoteMongoDBServiceTests/Sync/CoreDocumentSynchronizationConfigTests.swift
- Core/Services/StitchCoreRemoteMongoDBService/Tests/StitchCoreRemoteMongoDBServiceTests/Sync/CoreSyncUnitTests.swift
- Core/Services/StitchCoreRemoteMongoDBService/Tests/StitchCoreRemoteMongoDBServiceTests/Sync/DataSynchronizerUnitTests.swift
- Core/Services/StitchCoreRemoteMongoDBService/Tests/StitchCoreRemoteMongoDBServiceTests/Sync/InstanceSynchronizationConfigTests.swift
- Core/Services/StitchCoreRemoteMongoDBService/Tests/StitchCoreRemoteMongoDBServiceTests/Sync/NamespaceSynchronizationConfigTests.swift
- Core/StitchCoreSDK/Sources/StitchCoreSDK/Internal/Common/AuthMonitor.swift
- Core/StitchCoreSDK/Sources/StitchCoreSDK/Internal/Net/NetworkMonitor.swift
- Core/StitchCoreSDK/Sources/StitchCoreSDK/StitchError.swift
- Core/StitchCoreSDK/StitchCoreSDK.xcodeproj/project.pbxproj
Add the skeletons for CoreSync and DataSynchronizer. We (essentially) get the entirety CoreSync here for free, since on Swift, it is a simple delegate for the DataSynchronizer.
This includes the NetworkMonitor and AuthMonitor protocols.
I've also added an internal FatalErrorListener for the arbitrary lower-level errors that can occur due to MongoSwift or otherwise. It is meant to listen for "impossible states", and will pass along whatever information it can to the user.
Though the PR seems large, much of it is tests/comments, and many of the DataSynchronizer methods are stubs. This should allow us to not step on each other for future tickets.
> STITCH-2212 Swift SDK: Create a skeleton for sync operations and the data synchronizer

- Core/Services/StitchCoreRemoteMongoDBService/Sources/StitchCoreRemoteMongoDBService/Internal/CoreRemoteMongoReadOperation.swift
- Core/Services/StitchCoreRemoteMongoDBService/Tests/StitchCoreRemoteMongoDBServiceTests/CoreRemoteMongoCollectionUnitTests.swift
- Core/StitchCoreSDK/StitchCoreSDK.xcodeproj/project.pbxproj
- Darwin/Services/StitchRemoteMongoDBService/StitchRemoteMongoDBService/RemoteMongoReadOperation.swift
- Darwin/Services/StitchRemoteMongoDBService/StitchRemoteMongoDBServiceTests/RemoteMongoClientIntTests.swift
This ticket soft-deprecates the "asArray" method in the SDK in both the `CoreRemoteMongoReadOperation` and `RemoteMongoReadOperation` classes and adds a corresponding `toArray` method that does the same thing.
This change is intended to alleviate the issue that the Functions JS SDK differs from the other SDKs in this way.
The `asArray` function will stay in place at least until an appropriate time per semantic versioning guidelines (e.g. a major version upgrade).
> STITCH-2240 - add toArray, deprecate asArray

- Core/Services/StitchCoreRemoteMongoDBService/Sources/StitchCoreRemoteMongoDBService/Sync/CoreDocumentSynchronizationConfig.swift
- Core/Services/StitchCoreRemoteMongoDBService/Sources/StitchCoreRemoteMongoDBService/Sync/CoreSync.swift
- Core/Services/StitchCoreRemoteMongoDBService/Sources/StitchCoreRemoteMongoDBService/Sync/DataSynchronizer.swift
- Core/Services/StitchCoreRemoteMongoDBService/StitchCoreRemoteMongoDBService.xcodeproj/project.pbxproj
- Core/Services/StitchCoreRemoteMongoDBService/Tests/StitchCoreRemoteMongoDBServiceTests/Sync/CoreDocumentSynchronizationConfigTests.swift
- Core/Services/StitchCoreRemoteMongoDBService/Tests/StitchCoreRemoteMongoDBServiceTests/Sync/DataSynchronizerIntTests.swift
- Darwin/Services/StitchRemoteMongoDBService/StitchRemoteMongoDBService.xcodeproj/project.pbxproj
- Darwin/Services/StitchRemoteMongoDBService/StitchRemoteMongoDBService/Sync.swift
- Darwin/Services/StitchRemoteMongoDBService/StitchRemoteMongoDBServiceTests/RemoteMongoClientIntTests.swift
These are the implementation and tests for happy path delete. Also drove-by a fix to make the logicalT and lastResolution fields be `Int64` so they are properly encoded. This is not quite ready to be merged, since I believe I will need to add a few more tests once Jason merges STITCH-2215
> STITCH-2262 Happy path DELETE

- .evg.yml
- Core/StitchCoreSDK/Sources/StitchCoreSDK/Auth/Internal/CoreStitchAuth+ExternalRequests.swift
- Core/StitchCoreSDK/Sources/StitchCoreSDK/Auth/Internal/CoreStitchAuth.swift
- Core/StitchCoreSDK/StitchCoreSDK.xcodeproj/project.pbxproj
- Core/StitchCoreSDK/Tests/StitchCoreSDKTests/Internal/Net/StitchRequestClientUnitTests.swift
- contrib/lint_projects.sh
Adds a working lint task to evergreen.
This also drive-bys most of the necessary changes for STITCH-2266, but until the Evergreen team fixes the xcodebuild segfault problem on the hosts, STITCH-2266 can't be completed.
> STITCH-2268 add lint task to evergreen

- README.md
- contrib/publish_docs.sh
This updates the destination to a stitch-sdks subdirectory on the
existing bucket so that docs.mongodb.com/stitch-sdks can find it.
(Not sure, this was specifically required by techops.)
Removes the /docs/ part which is arguably redundant now that it is
hosted on docs.mongodb.com.
Also updates the README for the new docs URL. Please publish
the docs and check that the new URL works.
> DOCSP-3936 Push docs to docs.mongodb.com

- Core/Services/StitchCoreRemoteMongoDBService/Sources/StitchCoreRemoteMongoDBService/Sync/Internal/DataSynchronizer.swift
- Core/Services/StitchCoreRemoteMongoDBService/Sources/StitchCoreRemoteMongoDBService/Sync/Internal/InstanceChangeStreamDelegate.swift
- Darwin/Services/StitchRemoteMongoDBService/StitchRemoteMongoDBServiceTests/SyncIntTests.swift
- Darwin/StitchDarwinCoreTestUtils/StitchDarwinCoreTestUtils/BaseStitchIntTestCocoaTouch.swift
As per the Slack discussion, this PR fixes various issues with testing that caused a race condition in `testInsertInsertConflict`, and could have caused other issues in future tests. This should make the tests a lot more stable, and the test environment will more accurately reflect the real environment. This also matches more closely with how the tests work in the Android SDK
There were three issues:
1. `SyncTestContext.streamAndSync` was stopping the DataSynchronizer and starting the stream (via the `InstanceChangeStreamDelegate`) if the stream state was closed, but this was causing the stream to sometimes be opened more than once (setting documents stale in the process, causing the failing test), because the actual sync logic already starts the stream so it wasn't necessary. I changed …
> STITCH-2564 fix racy testInsertInsertConflict test by fixing some testing bugs

- Core/Services/StitchCoreRemoteMongoDBService/Sources/StitchCoreRemoteMongoDBService/Sync/Internal/DataSynchronizer.swift
- Darwin/Services/StitchRemoteMongoDBService/StitchRemoteMongoDBService.xcodeproj/project.pbxproj
- Darwin/Services/StitchRemoteMongoDBService/StitchRemoteMongoDBService/Sync+CRUD.swift
- Darwin/Services/StitchRemoteMongoDBService/StitchRemoteMongoDBService/Sync.swift
- Darwin/Services/StitchRemoteMongoDBService/StitchRemoteMongoDBServiceTests/RemoteMongoClientIntTests.swift
- Darwin/Services/StitchRemoteMongoDBService/StitchRemoteMongoDBServiceTests/SyncIntTests.swift
- Darwin/StitchDarwinCoreTestUtils/StitchDarwinCoreTestUtils/BaseStitchIntTestCocoaTouch.swift
This makes all the previously blocking sync calls async, and I also drive-by'ed the $in optimizaiton (STITCH-2585).
I did not yet do the optimization that sets is stale for a whole namespace rather than per document, so this will still be relatively slow on disconnect/reconnect until that optimization is made.
I've also moved the CRUD operations from `Sync.swift` into a `Sync+CRUD.swift` to keep the files small.
> STITCH-2559

- Core/StitchCoreSDK/Sources/StitchCoreSDK/Auth/Providers/Anonymous/AnonymousCredential.swift
- Core/StitchCoreSDK/Sources/StitchCoreSDK/Auth/Providers/Facebook/FacebookCredential.swift
- Core/StitchCoreSDK/Sources/StitchCoreSDK/Auth/Providers/Google/GoogleCredential.swift
- Core/StitchCoreSDK/Sources/StitchCoreSDK/Auth/Providers/UserPassword/UserPasswordCredential.swift
- Core/StitchCoreSDK/Sources/StitchCoreSDK/Auth/StitchCredential.swift
- Core/StitchCoreSDK/Sources/StitchCoreSDK/Auth/StitchUserIdentity.swift
- Core/StitchCoreSDK/Sources/StitchCoreSDK/Auth/StitchUserProfile.swift
- Darwin/StitchCore/StitchCore/Core/Auth/StitchAuth.swift
- Darwin/StitchCore/StitchCore/Core/Auth/StitchAuthDelegate.swift
- Darwin/StitchCore/StitchCore/Core/Auth/StitchUser.swift
- Darwin/StitchCore/StitchCore/Core/Stitch.swift
- Darwin/StitchCore/StitchCore/Core/StitchAppClient.swift
- Darwin/StitchCore/StitchCore/Core/StitchResult.swift
- contrib/stage_docs.sh
This adds See Also links and more content to the entities for the auth flow.
"See Also" is a bit weird on Jazzy. I tried using a bulleted list, but it ended up printing "SeeAlso:" twice... so I went with commas.
Staged:
https://docs-mongodbcom-staging.corp.mongodb.com/stitch/bush/docsp-4377-auth/sdk/swift/index.html
> DOCSP-4377 Auth flow

- contrib/README.md
- contrib/bump_version.sh
- contrib/publish_pods.sh
Just like the JS and Android PRs, this updates the `bump_version` script to open a PR with the necessary changes for a release to be made. I also updated the README to explain how the process goes after that.
> STITCH-2743 Update release scripts and README to follow new requirements

- Darwin/Services/StitchRemoteMongoDBService/StitchRemoteMongoDBService/RemoteMongoClient.swift
- Darwin/Services/StitchRemoteMongoDBService/StitchRemoteMongoDBService/RemoteMongoCollection.swift
- Darwin/Services/StitchRemoteMongoDBService/StitchRemoteMongoDBService/RemoteMongoCursor.swift
- Darwin/Services/StitchRemoteMongoDBService/StitchRemoteMongoDBService/RemoteMongoDatabase.swift
- Darwin/Services/StitchRemoteMongoDBService/StitchRemoteMongoDBService/RemoteMongoReadOperation.swift
- Darwin/Services/StitchRemoteMongoDBService/StitchRemoteMongoDBService/Sync.swift
- Darwin/StitchCore/StitchCore/Core/StitchAppClient.swift
This adds connecting links and content in the CRUD-related entities.
Start at StitchAppClient and navigate down to RemoteMongoCursor,
RemoteMongoReadOperation, and Sync.
Staged:
https://docs-mongodbcom-staging.corp.mongodb.com/stitch/bush/docsp-4379-crud/sdk/swift/index.html
> DOCSP-4379 Documentation improvements around CRUD flow

- Core/Services/StitchCoreRemoteMongoDBService/StitchCoreRemoteMongoDBService.xcodeproj/project.pbxproj
- Core/StitchCoreAdminClient/Sources/StitchCoreAdminClient/AuthProviders/ProviderConfig.swift
- Core/StitchCoreSDK/Sources/StitchCoreSDK/Auth/Providers/Apple/AppleAuthProvider.swift
- Core/StitchCoreSDK/Sources/StitchCoreSDK/Auth/Providers/Apple/AppleCredential.swift
- Core/StitchCoreSDK/Sources/StitchCoreSDK/Auth/StitchProviderType.swift
- Core/StitchCoreSDK/StitchCoreSDK.xcodeproj/project.pbxproj
- Darwin/StitchCore/StitchCore.xcodeproj/project.pbxproj
- Podfile.lock
- Add `AppleCredential` and `AppleAuthProvider` to `Auth` group
- Add apple as a `ProviderConfig` for Stitch Admin SDK
Note: Automated testing would be massive time sink (and likely incredibly brittle). I have tested this using Apple's example Apple Sign-in application. It works fine.
> STITCH-3632 add client sdk credentials for Apple sign in
